/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR 					0x40023800UL

#define RCC_AHB1_ENR_OFFSET 			0x30UL

#define RCC_AHB1_ENR_ADDR				(RCC_BASE_ADDR + RCC_AHB1_ENR_OFFSET)

#define RCC_CFGR_OFFSET					0x08UL

#define RCC_CFGR_ADDR					(RCC_BASE_ADDR + RCC_CFGR_OFFSET)

#define RCC_CR_ADDR						RCC_BASE_ADDR

#define GPIOA_BASE_ADDR 				0x40020000UL

#define GPIOA_MODER_ADDR				GPIOA_BASE_ADDR

#define GPIOA_AFRH_OFFSET				0x24UL

#define GPIOA_AFRH_ADDR					(GPIOA_BASE_ADDR + GPIOA_AFRH_OFFSET)
int main(void)
{
	uint32_t *pRccCr = (uint32_t*) RCC_CR_ADDR;
	uint32_t *pRccCfgr = (uint32_t*) RCC_CFGR_ADDR;
	uint32_t *pRccAhb1Enr = (uint32_t*) RCC_AHB1_ENR_ADDR;
	uint32_t *pGpioaModer = (uint32_t*) GPIOA_MODER_ADDR;
	uint32_t *pGpioaAfrh = (uint32_t*) GPIOA_AFRH_ADDR;

	//0. Enable HSE clock
	*pRccCr |= (0x1 << 16);
	//1. Configure the RCC_CFGR MCO1 bit fields to select HSE as clock source
	*pRccCfgr &= ~(0x3 << 21); //clear 21 and 22 bit positions
	*pRccCfgr |= (0x1 << 22); //set 22 bit position
	//Configure MCO1 prescaler
	*pRccCfgr |= (0x3 << 25);

	//2. Configure PA8 to AF0 mode to behave as MCO1 signal
	//a. Enable the peripheral clock for GPIOA peripheral
	*pRccAhb1Enr |= (0x1 << 0); //set 0 bit position
	//b. Configure the mode of GPIOA pin 8 as alternate function mode
	*pGpioaModer |= (0x2 << 16); //set 17 bit position
	*pGpioaModer &= ~(0x1 << 16); //clear 16 bit position
	//c. Configure the alternation function register to set the mode 0 for PA8
	*pGpioaAfrh &= ~(0xF << 0);

	return 0;
}
